prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT)^E_DEPRECATED)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ (E_NOTICE | E_DEPRECATED))."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # NOTE: OrangeHRM uses csrf_secret value stored in hs_hr_config, not the value below.
    csrf_secret:       'kafkasipi3#iadfsakf'     # Unique secret to enable CSRF protection or false to disable

    # Output escaping settings
    escaping_strategy:      true            # Determines how variables are made available to templates. Accepted values: on, off.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

    # Cache settings
    lazy_cache_key:         true        # Delays creation of a cache key until after checking whether an action or partial is cacheable

    standard_helpers:       [Partial, Cache, Orange, OrangeDate, Url, I18N, VersionCompatibility]

    login_module:           auth
    login_action:           login

    i18n:                   true
    default_culture: 		  en    # Default user culture

    enabled_modules:        [default, core, leave, pim, time, attendance, recruitment, recruitmentApply, admin, auth, dashboard, performance]

    # Charset used for the response
    charset:                utf-8
    
#all:
#  .actions:
#    error_404_module:       default   # To be called when a 404 error is raised
#    error_404_action:       error404  # Or when the requested URL doesn't match any route
#
#    login_module:           default   # To be called when a non-authenticated user
#    login_action:           login     # Tries to access a secure page
#
#    secure_module:          default   # To be called when a user doesn't have
#    secure_action:          secure    # The credentials required for an action
#
#    module_disabled_module: default   # To be called when a user requests 
#    module_disabled_action: disabled  # A module disabled in the module.yml
#
#  .settings:
#    # Optional features. Deactivating unused features boots performance a bit.
#    use_database:           true        # Enable database manager. Set to off if you don't use a database.
#    i18n:                   false       # Enable interface translation. Set to off if your application should not be translated.
#    check_symfony_version:  false       # Enable check of symfony version for every request. Set to on to have symfony clear the cache automatically when the framework is upgraded. Set to off if you always clear the cache after an upgrade.
#    compressed:             false       # Enable PHP response compression. Set to on to compress the outgoing HTML via the PHP handler.
#    check_lock:             false       # Enable the application lock system triggered by the clear-cache and disable tasks. Set to on to have all requests to disabled applications redirected to the $sf_symfony_lib_dir/exception/data/unavailable.php page.
#
#    # Routing settings
#    no_script_name:         false       # Enable the front controller name in generated URLs
#
#    # Validation settings, used for error generation by the Validation helper
#    validation_error_prefix:    ' &darr;&nbsp;'
#    validation_error_suffix:    ' &nbsp;&darr;'
#    validation_error_class:     form_error
#    validation_error_id_prefix: error_for_
#
#    # Cache settings
#    cache:                  false       # Enable the template cache
#    etag:                   true        # Enable etag handling
#    lazy_cache_key:         false       # Delays creation of a cache key until after checking whether an action or partial is cacheable (defaults to false for backward compatibility)
#
#    # Logging and debugging settings
#    web_debug:              false       # Enable the web debug toolbar
#    error_reporting:        <?php echo (E_PARSE | E_COMPILE_ERROR | E_ERROR | E_CORE_ERROR | E_USER_ERROR)."\n" ?> # Determines which events are logged.
#
#    # Assets paths
#    rich_text_js_dir:       js/tiny_mce
#    admin_web_dir:          /sf/sf_admin
#    web_debug_web_dir:      /sf/sf_web_debug
#    calendar_web_dir:       /sf/calendar
#
#    # Helpers included in all templates by default
#    standard_helpers:       [Partial, Cache, Form]
#
#    # Activated modules from plugins or from the symfony core
#    enabled_modules:        [default]
#
#    # Charset used for the response
#    charset:                utf-8
#
#    # Miscellaneous
#    strip_comments:         true         # Remove comments in core framework classes as defined in the core_compile.yml
#    max_forwards:           5
#
#    # Logging
#    logging_enabled:        true
#
#    # i18n
#    default_culture:        en        # Default user culture
