rendering: ~
security:  ~

# insert your own filters here
#exceptionCatcherFilter:
#  class: ExceptionCatcherFilter
i18nFilter:
  class: OrangeI18NFilter

cache:     ~
common:
  class: sfCommonFilter
execution: ~
