# default rules
homepage:
  url:   /
  param: { module: default, action: index }


 
location_list:
  url:   /admin/listCompanylocation/*  
  param: { module:admin, action: listCompanylocation }
  with_wildcard_routes: true

comproperty_list:
  url:   /admin/listCompanyProporty/*  
  param: { module:admin, action: listCompanyProporty }
  with_wildcard_routes: true
  
category_list:
  url:   /admin/listJobCategory/*  
  param: { module:admin, action: listJobCategory }
  with_wildcard_routes: true

salerygrade_list:
  url:   /admin/listSaleryGrade/*  
  param: { module:admin, action: listSaleryGrade }
  with_wildcard_routes: true

empstatus_list:
  url:   /admin/listEmployeeStatus/*  
  param: { module:admin, action: listEmployeeStatus }
  with_wildcard_routes: true

jobspec_list:
  url:   /admin/listJobSpecifications/*  
  param: { module:admin, action: listJobSpecifications }
  with_wildcard_routes: true

jobtitle_list:
  url:   /admin/listJobTitle/*  
  param: { module:admin, action: listJobTitle }
  with_wildcard_routes: true

license_list:
  url:   /admin/listLicenses/*  
  param: { module:admin, action: listLicenses }
  with_wildcard_routes: true

education_list:
  url:   /admin/listEducation/*  
  param: { module:admin, action: listEducation }
  with_wildcard_routes: true

skill_list:
  url:   /admin/listSkill/*  
  param: { module:admin, action: listSkill }
  with_wildcard_routes: true
  
language_list:
  url:   /admin/listLanguage/*  
  param: { module:admin, action: listLanguage }
  with_wildcard_routes: true

deleteMembershipType_list:
  url:   /admin/listMembershipType/*  
  param: { module:admin, action: listMembershipType }
  with_wildcard_routes: true

membershipType_list:
  url:   /admin/listMembershipType/*  
  param: { module:admin, action: listMembershipType }
  with_wildcard_routes: true

membership_list:
  url:   /admin/listMembership/*  
  param: { module:admin, action: listMembership }
  with_wildcard_routes: true

nationality_list:
  url:   /admin/listNationality/*  
  param: { module:admin, action: listNationality }
  with_wildcard_routes: true
  
ethnicRace_list:
  url:   /admin/listEthnicRace/*  
  param: { module:admin, action: listEthnicRace }
  with_wildcard_routes: true

project_list:
  url:   /admin/listProject/*  
  param: { module:admin, action: listProject }
  with_wildcard_routes: true

customer_list:
  url:   /admin/listCustomer/*  
  param: { module:admin, action: listCustomer }
  with_wildcard_routes: true

customfield_list:
  url:   /admin/listCustomFields/*  
  param: { module:admin, action: listCustomFields }
  with_wildcard_routes: true

usergroup_list:
  url:   /admin/listUserGroup/*  
  param: { module:admin, action: listUserGroup }
  with_wildcard_routes: true

user_list:
  url:   /admin/listUser/*  
  param: { module:admin, action: listUser }
  
performance_reviews:
  url:   /performance/viewReview/*  
  param: { module:performance, action: viewReview }

kpi_list:
  url:   /performance/listDefineKpi/*  
  param: { module:performance, action: listDefineKpi }
  
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

