default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  has_layout:     true
  layout:         freshorange

loginSuccess:
  layout: noHeader