all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=orangehrm_mysql;charset=utf8mb4'
      username: root
      password:
      attributes: { export: tables }
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=test_orangehrm_mysql;charset=utf8mb4'
      username: root
      password: 