name: Scheduled Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  db_test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        database: [ 'mysql:5.5', 'mysql:5.6', 'mysql:5.7', 'mysql:8.0', 'mariadb:5.5', 'mariadb:10.0', 'mariadb:10.1', 'mariadb:10.2', 'mariadb:10.3', 'mariadb:10.4', 'mariadb:10.5', 'mariadb:10.6', 'mariadb:10.7' ]

    services:
      mysql:
        image: ${{ matrix.database }}
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --name="database"

    env:
      WORKFLOW_BRANCH: ${{ secrets.WORKFLOW_BRANCH }}
    steps:
      - uses: actions/checkout@v2
        if: "${{ github.event_name != 'push' && env.WORKFLOW_BRANCH != '' }}"
        with:
          ref: ${{ secrets.WORKFLOW_BRANCH }}

      - uses: actions/checkout@v2
        if: "${{ github.event_name == 'push' || env.WORKFLOW_BRANCH == ''}}"

      - name: Source info
        run: |
          git log -1
          git remote -v

      - name: Install dependencies
        run: |
          php7.4 -f /usr/bin/composer install -d src
          php7.4 -f /usr/bin/composer install -d devTools/core

      - name: Install OrangeHRM
        run: |
          php7.4 installer/cli_install.php

      - name: Create Test DB on MySQL 8.0
        if: ${{ matrix.database == 'mysql:8.0' }}
        run: php7.4 devTools/core/console.php i:create-test-db -p root --dump-options="--column-statistics=0"

      - name: Create Test DB
        if: ${{ matrix.database != 'mysql:8.0' }}
        run: php7.4 devTools/core/console.php i:create-test-db -p root

      - name: Config sql_mode
        if: ${{ matrix.database == 'mysql:5.7' || matrix.database == 'mysql:8.0' }}
        run: docker exec database bash -c "mysql -uroot -proot -e \"SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));\""

      - name: Run test
        run: |
          ./src/vendor/bin/phpunit

  php_test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: [ 'php7.4', 'php8.0', 'php8.1' ]

    services:
      mysql:
        image: 'mariadb:5.5'
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          php7.4 -f /usr/bin/composer install -d src
          php7.4 -f /usr/bin/composer install -d devTools/core

      - name: Install OrangeHRM
        run: |
          ${{ matrix.php }} installer/cli_install.php
          ${{ matrix.php }} devTools/core/console.php i:create-test-db -p root

      - name: Run test
        run: |
          ${{ matrix.php }} ./src/vendor/bin/phpunit
